#!/bin/sh
# ==============================================================================
# Run logging cli
# ==============================================================================

echo "Waiting for the OS CLI to be ready..."

i=0
while [ ! "$(docker ps -q -f name=jhio_cli)" ]; do
    sleep 1
    i=$((i+1))
    if [ $i = 60 ]; then
        echo "[WARN] OS CLI not starting! Jump into emergency console..."
        exec /bin/ash -l
    fi
done

docker container exec \
    -ti jhio_cli \
    /usr/bin/cli.sh

case $? in
  10)
    # Jump to root login shell (login command)
    exec /bin/ash -l
    ;;
  143)
    # 143 graceful termination (SIGTERM). Most likely a proper shutdown.
    # Just sleep for a while until actual systemd shutdown gets invoked.
    echo ""
    echo "OS CLI has been terminated."
    sleep 30
    ;;
  *)
    echo "HA CLI failed with error code: $?"
    ;;
esac
